# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'segmentation_refine_form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QLabel, QListWidget, QListWidgetItem, QPushButton,
    QRadioButton, QSizePolicy, QSlider, QSpinBox,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1450, 850)
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 1431, 831))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.frame = QFrame(self.tab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 1181, 681))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayoutWidget = QWidget(self.frame)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 1161, 651))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_loadSlices = QPushButton(self.tab)
        self.pushButton_loadSlices.setObjectName(u"pushButton_loadSlices")
        self.pushButton_loadSlices.setGeometry(QRect(1250, 30, 111, 31))
        self.spinBox_sliceNum = QSpinBox(self.tab)
        self.spinBox_sliceNum.setObjectName(u"spinBox_sliceNum")
        self.spinBox_sliceNum.setGeometry(QRect(30, 735, 101, 31))
        self.spinBox_sliceNum.setMaximum(1000000)
        self.slider_sliceNum = QSlider(self.tab)
        self.slider_sliceNum.setObjectName(u"slider_sliceNum")
        self.slider_sliceNum.setGeometry(QRect(145, 739, 331, 22))
        self.slider_sliceNum.setMaximum(1000000)
        self.slider_sliceNum.setOrientation(Qt.Orientation.Horizontal)
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(667, 710, 331, 71))
        self.radioButton_zDir = QRadioButton(self.groupBox)
        self.radioButton_zDir.setObjectName(u"radioButton_zDir")
        self.radioButton_zDir.setGeometry(QRect(230, 30, 92, 20))
        self.radioButton_zDir.setChecked(True)
        self.radioButton_yDir = QRadioButton(self.groupBox)
        self.radioButton_yDir.setObjectName(u"radioButton_yDir")
        self.radioButton_yDir.setGeometry(QRect(130, 30, 92, 20))
        self.radioButton_xDir = QRadioButton(self.groupBox)
        self.radioButton_xDir.setObjectName(u"radioButton_xDir")
        self.radioButton_xDir.setGeometry(QRect(30, 30, 92, 20))
        self.radioButton_xDir.setChecked(False)
        self.spinBox_brushSize = QSpinBox(self.tab)
        self.spinBox_brushSize.setObjectName(u"spinBox_brushSize")
        self.spinBox_brushSize.setGeometry(QRect(1312, 201, 81, 22))
        self.spinBox_brushSize.setMinimum(1)
        self.spinBox_brushSize.setMaximum(30)
        self.spinBox_brushSize.setValue(6)
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1232, 201, 71, 20))
        self.spinBox_segId = QSpinBox(self.tab)
        self.spinBox_segId.setObjectName(u"spinBox_segId")
        self.spinBox_segId.setGeometry(QRect(1312, 250, 81, 22))
        self.spinBox_segId.setMaximum(255)
        self.spinBox_segId.setSingleStep(1)
        self.spinBox_segId.setValue(0)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1232, 250, 71, 20))
        self.pushButton_loadMasks = QPushButton(self.tab)
        self.pushButton_loadMasks.setObjectName(u"pushButton_loadMasks")
        self.pushButton_loadMasks.setEnabled(False)
        self.pushButton_loadMasks.setGeometry(QRect(1250, 80, 111, 31))
        self.pushButton_saveMasks = QPushButton(self.tab)
        self.pushButton_saveMasks.setObjectName(u"pushButton_saveMasks")
        self.pushButton_saveMasks.setGeometry(QRect(1250, 130, 111, 31))
        self.checkBox_overlaySegMask = QCheckBox(self.tab)
        self.checkBox_overlaySegMask.setObjectName(u"checkBox_overlaySegMask")
        self.checkBox_overlaySegMask.setGeometry(QRect(500, 738, 151, 20))
        self.checkBox_overlaySegMask.setChecked(True)
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(37, 708, 81, 20))
        self.listWidget_segIdPaletteList = QListWidget(self.tab)
        self.listWidget_segIdPaletteList.setObjectName(u"listWidget_segIdPaletteList")
        self.listWidget_segIdPaletteList.setGeometry(QRect(1224, 308, 171, 211))
        self.label_curPos = QLabel(self.tab)
        self.label_curPos.setObjectName(u"label_curPos")
        self.label_curPos.setGeometry(QRect(1328, 738, 81, 20))
        self.label_curSegID = QLabel(self.tab)
        self.label_curSegID.setObjectName(u"label_curSegID")
        self.label_curSegID.setGeometry(QRect(1328, 766, 81, 20))
        self.checkBox_showAxis = QCheckBox(self.tab)
        self.checkBox_showAxis.setObjectName(u"checkBox_showAxis")
        self.checkBox_showAxis.setGeometry(QRect(1026, 738, 91, 20))
        self.checkBox_showAxis.setChecked(True)
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(1214, 540, 191, 151))
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 73, 71, 16))
        self.spinBox_curBlobID = QSpinBox(self.groupBox_2)
        self.spinBox_curBlobID.setObjectName(u"spinBox_curBlobID")
        self.spinBox_curBlobID.setGeometry(QRect(101, 34, 71, 22))
        self.spinBox_curBlobID.setMaximum(255)
        self.pushButton_updateBlobID = QPushButton(self.groupBox_2)
        self.pushButton_updateBlobID.setObjectName(u"pushButton_updateBlobID")
        self.pushButton_updateBlobID.setGeometry(QRect(100, 105, 75, 24))
        self.spinBox_newBlobID = QSpinBox(self.groupBox_2)
        self.spinBox_newBlobID.setObjectName(u"spinBox_newBlobID")
        self.spinBox_newBlobID.setGeometry(QRect(101, 70, 71, 22))
        self.spinBox_newBlobID.setMaximum(255)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 37, 71, 16))
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"AI Segmentation Review", None))
        self.pushButton_loadSlices.setText(QCoreApplication.translate("Form", u"Load slices", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"Slice direction", None))
        self.radioButton_zDir.setText(QCoreApplication.translate("Form", u"along Z", None))
        self.radioButton_yDir.setText(QCoreApplication.translate("Form", u"along Y", None))
        self.radioButton_xDir.setText(QCoreApplication.translate("Form", u"along X", None))
        self.label.setText(QCoreApplication.translate("Form", u"Brush (-=) :", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Seg ID ([]) :", None))
        self.pushButton_loadMasks.setText(QCoreApplication.translate("Form", u"Load masks", None))
        self.pushButton_saveMasks.setText(QCoreApplication.translate("Form", u"Save masks", None))
        self.checkBox_overlaySegMask.setText(QCoreApplication.translate("Form", u"Overlay seg mask (Rt)", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Slice num (;') :", None))
        self.label_curPos.setText(QCoreApplication.translate("Form", u"Pos (0, 0)", None))
        self.label_curSegID.setText(QCoreApplication.translate("Form", u"Seg ID = 0", None))
        self.checkBox_showAxis.setText(QCoreApplication.translate("Form", u"Show Axis", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Form", u"Edit Blob ID ", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"New Blob ID:", None))
        self.pushButton_updateBlobID.setText(QCoreApplication.translate("Form", u"Update", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Cur Blob ID:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"Slice View", None))
    # retranslateUi

